upgradeCompatibility: '1.8'
debug:
  enabled: true
  verbose: flow

k8sServiceHost: "192.168.105.100"
k8sServicePort: "6443"

k8sClientRateLimit:
  qps: 50
  burst: 100

cluster:
  name: k8smac
  id: 0

serviceAccounts:
  nodeinit:
    create: false
  preflight:
    create: false
  clustermeshApiserver:
    create: false
  clustermeshcertgen:
    create: false
  relay:
    automount: true

rollOutCiliumPods: true

autoDirectNodeRoutes: true
directRoutingSkipUnreachable: true
annotateK8sNode: true

l2announcements:
  enabled: true

bpf:
  autoMount:
    enabled: false
  root: /sys/fs/bpf
  masquerade: false

waitForKubeProxy: false

cni:
  exclusive: false
  iptablesRemoveAWSRules: false

enableK8sEndpointSlice: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  enforceHttps: false
  service:
    annotations:
      "io.cilium/lb-ipam-ips": "192.168.105.254"

gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"

socketLB:
  hostNamespaceOnly: true

hubble:
  enabled: true
  redact:
    enabled: true
    http:
      urlQuery: false
  preferIpv6: false
  tls:
    enabled: false
  relay:
    enabled: true
    rollOutPods: true
    replicas: 1
  ui:
    enabled: true
    rollOutPods: true
    frontend:
      server:
        ipv6:
          enabled: false
    replicas: 1

ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]
    clusterPoolIPv4MaskSize: 24

ipv4:
  enabled: true

ipv6:
  enabled: false

k8s:
  requireIPv4PodCIDR: true
  requireIPv6PodCIDR: false

kubeProxyReplacement: true

egressGateway:
  enabled: false

ipv4NativeRoutingCIDR: "10.244.0.0/16"

envoy:
  enabled: true
  rollOutPods: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
  debug:
    admin:
      enabled: true
  prometheus:
    enabled: false

routingMode: native

operator:
  enabled: true
  rollOutPods: true
  replicas: 1
  prometheus:
    enabled: false

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

disableEnvoyVersionCheck: true
