k8sServiceHost: "192.168.105.100"
k8sServicePort: "6443"

kubeProxyReplacement: true

rollOutCiliumPods: true

gatewayAPI:
  enabled: true

l2announcements:
  enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]

k8sClientRateLimit:
  qps: 50
  burst: 100

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      "io.cilium/lb-ipam-ips": "192.168.105.254"

operator:
  enabled: true
  replicas: 1
  rollOutPods: true

envoy:
  enabled: true
  rollOutPods: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
