apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
- token: "9a08jv.c0izixklcxtmnze7"
  description: "Initial bootstrap token for the first time setup of a kubernetes cluster"
  ttl: "1h"
  usages:
  - authentication
  - signing
  groups:
  - system:bootstrappers:kubeadm:default-node-token
certificateKey: "c411505d8504115b928286cc37a83c230d80c4db06bdf19d8f64828e3724d363"
localAPIEndpoint:
  advertiseAddress: 192.168.105.101
  bindPort: 6443
nodeRegistration:
  name: "cp-1"
  criSocket: "unix:///var/run/containerd/containerd.sock"
  imagePullPolicy: "IfNotPresent"
  imagePullSerial: false
  ignorePreflightErrors:
    - NumCPU
    - Mem
  kubeletExtraArgs:
  - name: node-ip
    value: 192.168.105.101
skipPhases:
  - addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: "sandbox"
controlPlaneEndpoint: 192.168.105.100:6443
featureGates:
kubernetesVersion: 1.32.6
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/16"
  dnsDomain: "cluster.local"
proxy:
  disabled: true
apiServer:
  certSANs:
  - "127.0.0.1"
  - "192.168.105.100"
  - "192.168.105.101"
  - "192.168.105.102"
  - "192.168.105.103"
  - "sandbox"
  extraArgs:
  - name: event-ttl
    value: 3h0m0s
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
rotateCertificates: true
serverTLSBootstrap: true
serializeImagePulls: false
featureGates:
