apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 192.168.105.103
    bindPort: 6443
  certificateKey: "c411505d8504115b928286cc37a83c230d80c4db06bdf19d8f64828e3724d363"
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.105.100:6443
    token: 9a08jv.c0izixklcxtmnze7
    unsafeSkipCAVerification: true
nodeRegistration:
  name: "cp-3"
  criSocket: "unix:///var/run/containerd/containerd.sock"
  kubeletExtraArgs:
  - name: node-ip
    value: 192.168.105.103
  ignorePreflightErrors:
    - NumCPU
    - Mem
