apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.105.100:6443
    token: 9a08jv.c0izixklcxtmnze7
    unsafeSkipCAVerification: true
nodeRegistration:
  name: "worker-3"
  criSocket: "unix:///var/run/containerd/containerd.sock"
  kubeletExtraArgs:
  - name: node-ip
    value: 192.168.105.106
  ignorePreflightErrors:
